import Head from 'next/head'
import Image from 'next/image'
import Questions, { getServerSideProps as getServerSidePropsQuestions} from './questions';
import styles from '../styles/Home.module.css'


export function getServerSideProps(context) {
  return getServerSidePropsQuestions(context);
}

export default function Home(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Questions {...props} />
      
    </div>
  )
}
